name: Deploy Staging
on:
  push:
    branches:
      - expo-web
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying started"
      - run: |
        cd mobile/mobile |
        yarn |
        yarn web:prod-github |
        ./deploy-staging.sh
