name: Deploy Staging
on:
  push:
    branches:
      - expo-web
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying started"
      - run: yarn
      - run: yarn web:prod-github
      - run: ./deploy-staging.sh
